### ISSUE TITLE
Sprockets Error: couldn't find file 'aloha'

### ISSUE THREAD

**Issue by jscheel** [locomotivecms/aloha-rails#1]
require in my application.js can't find aloha

**Comment by jscheel** [comment]
Looks like the css loads properly, at least if I visit: http://localhost/assets/aloha.css

**Comment by kmendes** [comment]
Same problem here....

**Comment by ccastillop** [comment]
I guess there is 'aloja-rails' gem name conflict with this one: https://github.com/Skalar/aloha-rails

Althought, I tried with `gem 'locomotive-aloha-rails'` instead, as described inside https://github.com/locomotivecms/aloha-rails/blob/master/locomotive-aloha-rails.gemspec, without success.

Something is outdated at the instructions :(

**Comment by dukedorje** [comment]
here too

**Comment by dukedorje** [comment]
//= require aloha/lib/aloha

So far there are still issues with the url paths in the aloha.css... they do not play nicely with asset-paths or anything.  I think I'm just going to install it manually.

**Comment by ghost** [comment]
+1 .. same issue , going also to install it manually

**Comment by did** [comment]
I fixed it. thanks guys.
