### ISSUE TITLE
Aloha not found

### ISSUE THREAD

**Issue by Hengjie** [locomotivecms/aloha-rails#4]
I followed the instructions on the `README` file and here's the error I get:

```
couldn't find file 'aloha'
  (in /root/app/assets/javascripts/application.js.erb:24)
```

I have bundled installed and restarted foreman already.

**Comment by Hengjie** [comment]
hmm... So bundler seems to be picking up an old version of this gem:

`Using locomotive-aloha-rails (0.20.1.5)`

**Comment by Hengjie** [comment]
I've decreased the Rails version requirement of `3.2.13` to `3.2.12` which means I am now on the latest version of the Aloha Rails gem and it is still causing the same issues.

https://github.com/Hengjie/aloha-rails/commit/50496b090dbaa284c0ac3021afb6339b11ea2e4d

**Comment by Hengjie** [comment]
Adding `:remove => "aloha-rails"` works

```
gem 'locomotive-aloha-rails', "~> 0.23.2.1", :git => 'git://github.com/Hengjie/aloha-rails.git', :require => "aloha-rails"
```

**Comment by did** [comment]
hey @Hengjie, that's right ! I've upgraded the doc. thanks !
