### ISSUE TITLE
Chrome detection

### ISSUE THREAD

**Issue by kayakyakr** [locomotivecms/aloha-rails#7]
Jquery version detection in chrome changed, breaking the ability of aloha 0.23.2 to determine if it's a chrome browser. This is updated in the current version of Aloha (0.23.6). For that reason, I'm not going to issue a pull request on my forked hotfix.

**Comment by did** [comment]
hey @kayakyakr, Aloha does not work with jQuery versions >= 1.8 as far as I know. A work-around would be to load jQuery 1.7.x before Aloha.

```
#= require aloha/lib/require
#= require aloha/lib/vendor/jquery-1.7.2
#= require aloha/lib/vendor/jquery-ui-1.9.0.custom-aloha
#= require aloha
```
